# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#demo_one'
    weight: 10
  - name: People
    url: 'people/'
    weight: 20
  #- name: Posts
  #  url: '#posts'
  #  weight: 30
  - name: Research
    url: 'page/research'
    weight: 30
  #- name: Talks
  #  url: '#talks'
  #  weight: 50
  - name: Publications
    url: 'publication/'
    weight: 40
  - name: Resources
    url: resources
    weight: 50
  - name: Friends
    url: 'page/friends/'
    weight: 1
  - name: Meetings
    url: 'page/meetings/'
    weight: 2
  - name: Societies
    url: 'page/societies/'
    weight: 3
  - name: Journals
    url: 'page/journals/'
  - name: Tools
    url: 'page/tools/'
    weight: 4
  - name: Join the Lab
    identifier: join
    weight: 60
  - name: Fellowships
    parent: join
    url: 'page/fellowships/'
    weight: 1
  - name: Internships
    parent: join
    url: 'page/internships/'
    weight: 2
  - name: Contact
    parent: join
    url: '#contact'
    weight: 3

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
